/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "BsPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BsPoster": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "BsUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
